services:
  - type: web
    name: alurachallengebackend5
    env: node
    plan: free
    buildCommand:
      yarn install &&
      yarn prisma generate &&
      yarn prisma migrate deploy &&
      yarn prisma db seed
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: acbe5-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: acbe5-db
    plan: free