services:
  - type: web
    name: alurachallengebackend5
    env: node
    plan: free
    buildCommand:
      npm --frozen-lockfile --prod=false &&
      npm prisma generate &&
      npm build &&
      npx prisma migrate deploy &&
      npx prisma db seed
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: acbe5-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: acbe5-db
    plan: free