services:
  - type: web
    name: alurachallengebackend5
    env: node
    plan: free
    buildCommand:
      yarn --frozen-lockfile --prod=false &&
      yarn prisma generate &&
      yarn prisma db seed &&
      yarn build &&
      yarn prisma migrate deploy
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: acbe5-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true

databases:
  - name: acbe5-db
    plan: free